apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubehealth-api-deployment
  labels:
    app: kubehealth-api
spec:
  selector:
    matchLabels:
      app: kubehealth-api
  template:
    metadata:
      labels:
        app: kubehealth-api
    spec:
      containers:
      - name: kubehealth-api
        image: luisalexandrerodrigues/kubehealth:latest
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: health/startup
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: health/status/liveness
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: health/status/readiness
            port: 80
          successThreshold: 3
