apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubehealth-api-deployment
  labels:
    app: kubehealth-api
spec:
  selector:
    matchLabels:
      app: kubehealth-api
  template:
    metadata:
      labels:
        app: kubehealth-api
    spec:
      containers:
      - name: kubehealth-api
        image: luisalexandrerodrigues/kubehealth:latest
        ports:
        - containerPort: 80
