apiVersion: v1
kind: Pod
metadata:
  name: kubehealth-api
  labels:
    app: kubehealth-api
spec:
  containers:
  - name: kubehealth-api
    image: luisalexandrerodrigues/kubehealth:latest
    ports:
    - containerPort: 80
